### ISSUE TITLE
Missins Visual Studio Solution

### ISSUE THREAD

**Issue by toasti1973** [nicolasbertoa/D3D12Base#1]
Nice Project, but I miss the Visual Studio Solution-File

**Comment by nbertoa** [comment]
You are right. My apologies, tonight I will upload the VS solution and I will let you know.


Thanks!

________________________________

**Comment by nbertoa** [comment]
Did you check the solution is there?

**Comment by toasti1973** [comment]
Hello,

 

Sorry for the late answer, I´m a little bit bussy.

 

This Night I have downloaded the full Solution, and it works !

 

I realy like your Project, the only Project with a realy DX12 Multithreading solution I know !

 

Thank you

 

Von: nicolasbertoa [mailto:notifications@github.com] 
Gesendet: Montag, 2. Januar 2017 01:37
An: nicolasbertoa/BRE12 <BRE12@noreply.github.com>
Cc: toasti1973 <thorsten.polte@freenet.de>; Author <author@noreply.github.com>
Betreff: Re: [nicolasbertoa/BRE12] Missins Visual Studio Solution (#1)

 

Did you check the solution is there?

**Comment by nbertoa** [comment]
Good to know that!


If you find something to improve or a bug, please let me know.

________________________________
